### ISSUE TITLE
Set the title dynamically

### ISSUE THREAD

**Issue by MahbodHastam** [artesaos/seotools#278] opened 2022-07-22 06:27 UTC
How do I set the website title dynamically from the database or another config file?
`SeoTools::setTitle()` only changes the page title

**Comment by J-Brk** [comment] 2022-08-27 20:48
By integrating `SeoTools::setTitle()` into your application and using the generator in the blade as explained in the documentation. Closing this issue since it's not an issue with this package.

**Closed by J-Brk** 2022-08-27 20:48 UTC

**Comment by Rattone** [comment] 2023-09-20 19:55
I'm reopening this issue because I believe that the problem is in changing the "title" (e.g. site name) positioned after the separator.
I'm having the same problem, I would like to dynamically change the "seotools.meta.defaults.title" config.
I can do it in service provider but I can't do it in middleware or controller.
If this is not possible I will have to manage this manually for each page
